<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Authentification - Authentification</title>
</head>
<body>
    <h3>Authentification</h3>
    <div>
        <form action="authentification.php" method="post">
            <input type="text" name="pseudo" placeholder="Pseudonyme">
            <input type="password" name="mdpHash" placeholder="Mot de passe">
            <button type="submit">Authentification</button>
        </form>
    </div>
    <a href="index.php">Retour à l'accueil</a><br>
</body>
</html>