<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="./css/index.css">
    <title>Blog Communautaire</title>
</head>
<body>
    <header>
        <a href="./inscription.php">Inscription</a> <br>
        <a href="./authentification.php">Authentification</a>
    </header>
    <h2>Blog communautaire</h2>
    <div>
        <p>Posts récents</p>
        <div class="post">
            <?php foreach($posts as $post): ?>
            <?php var_dump($post['image'])?>
            <div class="blanc">
                <img src="./img/<?=$post['image']?>">
                <h3> <?= $post['titre']?></h3>
                <h4> <?= $post['datePublication']?></h3>
                <a href="#">Détails post</a> <!-- méthode GET ?? -->
            </div>
            <?php endforeach ?>
        </div>
    </div>
</body>
</html>