<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Authentification - Inscription</title>
</head>
<body>
<h3>Inscription</h3>
    <div>
        <form action="inscription.php" method="post">
            <input type="text" name="pseudo" placeholder="Pseudonyme">
            <input type="password" name="mdpHash" placeholder="Mot de passe">
            <button type="submit">Inscription</button>
        </form>
    </div>
    <br>
    <a href="index.php">Retour à l'accueil</a>
</html>