<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="./css/inscription.css">
    <title>Inscription</title>
</head>
<body>
    <div class="bloc">
        <div class="h3">
            <h3>Inscription</h3>
        </div>
        <div class="div">
            <form action="inscription.php" method="post">
                <input type="text" name="pseudo" placeholder="Pseudonyme">
                <input type="password" name="mdpHash" placeholder="Mot de passe">
                <button type="submit">Inscription</button>
            </form>
        </div>

        <div class="lien">
            <a href="index.php">Retour à l'accueil</a>
        </div>
    </div>
</body>
</html>