<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mon compte</title>
</head>
<body>
    <p>BIENVENUE</p>
    <div>
        <form action="monCompte.php" method="post" enctype="multipart/form-data" accept="image/png, image/jpeg">
            <input type="text" name="titre" placeholder="Titre">
            <input type="file" name="fichier" placeholder="URL">
            <input type="hidden" name="MAX_FILE_SIZE" value="3000000">
            <input type="text" name="contenu" placeholder="Contenu">
            <button type="submit">Envoyer</button>
        </form>
    </div>
    <footer>
        <a href="./">Accueil</a>
    </footer>
</body>
</html>